### ISSUE TITLE
Cannot connect to Jekyll running in docker with default _config.yml

### ISSUE THREAD

**Issue by rogermarlow** [rockstorm101/jekyll-docker#1]
With the default config that Jekyll provides from `jekyll build`, webrick binds to `127.0.0.1:4000`, and hence says `Server address: http://127.0.0.1:4000/` in the log when it is run with `jekyll serve`. This is fine when running Jekyll natively on the host and connecting to it from a browser on the same host.

With Jekyll inside a container and `127.0.0.1` being the loopback interface, it is only accessible from within the container. A browser running on the Docker host makes no connection. If you try to connect from curl you get `curl: (56) Recv failure: Connection reset by peer`. After much messing around with the `EXPOSE 4000` statement in the Docker file I ran a shell in the Jekyll container, installed the `iproute2` package and ran `ss -ptl` which shows:
```
/srv/jekyll # ss -ptl
State           Recv-Q          Send-Q                    Local Address:Port                     Peer Address:Port          Process
LISTEN          0               128                           127.0.0.1:4000                          0.0.0.0:*              users:(("bundler",pid=1,fd=11))
``` 
proving that the Jekyll process is only listening for connections coming via 127.0.0.1, i.e. from within the same container. You can also prove this by running `curl localhost:4000` within the container which receives a load of HTML, whereas it does not even connect from the host.

As I see it there are at least two possible fixes. Either add a note in the README.md instructing the user to add an entry `host: 0.0.0.0` to their `_config.yml` after the initial `jekyll build`,  or change the `ENTRYPOINT` statement in the Dockerfile provided by this repo to `ENTRYPOINT ["bundler", "exec", "jekyll", "--host", "0.0.0.0"]`.

**Comment by rockstorm101** [comment]
Hi @rogermarlow, thanks for your detailed report. I'm not sure I fully understand the problem. The command given on the [README][1] for serving the blog already contains the `--host 0.0.0.0` bit that would allow access from outside the container. Isn't that enough? I don't see the need to add it to the entrypoint. Using the steps in the README I can access the blog just fine, so maybe I need some help on reproducing the issue.

Asking users to set up their host (i.e. modify their `_config.yml`) just to use this container I don't think is good since they might need that to deploy somewhere else after building. So definitely we need other solutions.

[1]: https://github.com/rockstorm101/jekyll-docker?tab=readme-ov-file#2-build--serve-your-blog

**Comment by rogermarlow** [comment]
Yep, my bad. The way the markdown is rendered, it is not obvious that single line code snippets are scrollable, so when I copied it by eye rather than using the copy and paste button I didn't see the `--host 0.0.0.0` at the end. Perhaps consider making that a multi-line code fence with each option on its own line? It might also be worth a line or two of explanation as to why it is necessary?

**Comment by rockstorm101** [comment]
> Perhaps consider making that a multi-line code fence with each option on its own line? It might also be worth a line or two of explanation as to why it is necessary?

Fair enough. Done. Many thanks for your contribution.
